-- Supabase schema for WeezMon
create extension if not exists pgcrypto;

create table if not exists companies (
  id uuid primary key default gen_random_uuid(),
  name text,
  company_guid text,
  api_token text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists events (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references companies(id),
  event_guid text,
  name text,
  start_date timestamptz,
  end_date timestamptz
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  event_id uuid references events(id),
  total numeric,
  status text,
  created_at timestamptz default now()
);

create table if not exists refunds (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references orders(id),
  amount numeric,
  status text,
  created_at timestamptz default now()
);

create table if not exists api_logs (
  id bigint generated by default as identity primary key,
  company_id uuid,
  endpoint text,
  status_code integer,
  response_time numeric,
  created_at timestamptz default now()
);

-- Additional helper tables used by the app
create table if not exists report_logs (
  id bigint generated by default as identity primary key,
  company_guid text,
  total_sales numeric,
  total_refunds numeric,
  created_at timestamptz default now()
);

create table if not exists finance_snapshots (
  id bigint generated by default as identity primary key,
  company_guid text,
  payload jsonb,
  created_at timestamptz default now()
);
