version: "3.9"

services:
  fastapi:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r backend/requirements.txt && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - EVENTIX_API_BASE=${EVENTIX_API_BASE}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r backend/requirements.txt && celery -A backend.celery_app.celery_app worker --loglevel=info"
    volumes:
      - ./:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - EVENTIX_API_BASE=${EVENTIX_API_BASE}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase.db
